from sc2.ids.unit_typeid import UnitTypeId as UnitID

ATTACK_TARGET_IGNORE: set[UnitID] = {
    UnitID.SCV,
    UnitID.DRONE,
    UnitID.PROBE,
    UnitID.MULE,
    UnitID.LARVA,
    UnitID.EGG,
    UnitID.CHANGELING,
    UnitID.CHANGELINGMARINE,
    UnitID.CHANGELINGMARINESHIELD,
    UnitID.CHANGELINGZEALOT,
    UnitID.CHANGELINGZERGLING,
    UnitID.CHANGELINGZERGLINGWINGS,
    UnitID.REAPER,
}

BIO_FORCES: set[UnitID] = {
    UnitID.MARINE,
    UnitID.MARAUDER,
    UnitID.MEDIVAC,
}

COMMON_UNIT_IGNORE_TYPES: set[UnitID] = {
    UnitID.EGG,
    UnitID.LARVA,
    UnitID.CREEPTUMORBURROWED,
    UnitID.CREEPTUMORQUEEN,
    UnitID.CREEPTUMOR,
    UnitID.MULE,
}

UNITS_TO_IGNORE: set[UnitID] = {
    # Zerg
    UnitID.CHANGELING,
    UnitID.CHANGELINGMARINE,
    UnitID.CHANGELINGMARINESHIELD,
    UnitID.CHANGELINGZEALOT,
    UnitID.CHANGELINGZERGLING,
    UnitID.CHANGELINGZERGLINGWINGS,
    UnitID.DRONE,
    UnitID.EGG,
    UnitID.INFESTEDTERRAN,
    UnitID.INFESTEDTERRANSEGG,
    UnitID.LARVA,
    UnitID.OVERLORD,
    UnitID.OVERLORDCOCOON,
    UnitID.OVERLORDTRANSPORT,
    UnitID.OVERSEER,
    # Protoss
    UnitID.PROBE,
    # Terran
    UnitID.MULE,
    UnitID.SCV,
}

TOWNHALL_TYPES: set[UnitID] = {
    UnitID.HATCHERY,
    UnitID.LAIR,
    UnitID.HIVE,
    UnitID.COMMANDCENTER,
    UnitID.COMMANDCENTERFLYING,
    UnitID.ORBITALCOMMAND,
    UnitID.ORBITALCOMMANDFLYING,
    UnitID.PLANETARYFORTRESS,
    UnitID.NEXUS,
}
